version: 2

jobs:
 build:
   machine: true
   working_directory: ~/workspace

   steps:
     - checkout

     - run:
         name: Build docker image
         command: |
           docker build -t django-base .
     - run:
         name: Tagging
           docker tag django-base ${CIRCLE_USERNAME}/django-base:latest
           docker tag django-base ${CIRCLE_USERNAME}/django-bases:${CIRCLE_SHA1:0:6}
     - run:
         name: Push to docker hub
         command: |
           docker login -u $DOCKER_LOGIN_ID -p $DOCKER_LOGIN_PASSWORD
           docker push ${CIRCLE_USERNAME}/django-bases:${CIRCLE_SHA1:0:6}
           docker push ${CIRCLE_USERNAME}/django-base:latest

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
